# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.3
  - 3.4
  - 2.7
  - 2.6

env:
  matrix:
  - DJANGO='django>=1.5,<1.6'
  - DJANGO='django>=1.6,<1.7'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt

# command to run tests, e.g. python setup.py test
script: coverage run djangocms-helper djangocms_blog test --cms --nose

after_success: coveralls

matrix:

  allow_failures:
    - python: 3.3
      env: DJANGO='django>=1.5,<1.6'
    - python: 3.3
      env: DJANGO='django>=1.6,<1.7'
    - python: 3.4
      env: DJANGO='django>=1.5,<1.6'
    - python: 3.4
      env: DJANGO='django>=1.6,<1.7'